version: '3'
services:
  frontend:
    image: node:18
    container_name: ngcash_front
    tty: true
    stdin_open: true
    command: bash
    # command: npm run dev  // ENTREGAR COM ESTE COMANDO
    restart: always
    working_dir: /ng-cash/frontend
    volumes:
      - ./frontend:/ng-cash/frontend
    depends_on:
      - backend
    ports:
      - 5173:5173
    environment:
      REACT_APP_HOST: backend
    networks:
      - ngcash_net

  backend:
    image: node:18
    container_name: ngcash_back
    tty: true
    stdin_open: true
    command: bash
    # command: npm run start  // ENTREGAR COM ESTE COMANDO
    restart: always
    working_dir: /ng-cash/backend
    volumes:
      - ./backend:/ng-cash/backend
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      POSTGRES_HOST: db
      PORT: 3001
      NODE_ENV: 'development'
      JWT_SECRET: 'secret'
    networks:
      - ngcash_net

  db:
    container_name: ngcash_db
    image: postgres
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - ngcash_net
  
networks:
  ngcash_net:
    driver: bridge